Solution
Shubham-Porwall/Ruby-Basic pull request #1
Opened 2022-01-20 09:22 UTC by Shubham-Porwall

Hi Kalpana Ma'am,

Creating this pull request for reviewing the solutiobn

2022-01-20 11:33 UTC, kalpana19sharma requested changes
@Shubham-Porwall Use proper heading for your PR.

2022-01-20 11:33 UTC, kalpana19sharma commented on file_manage.rb
> +afile = File.open("test.rb","r+")
Space after `,`

2022-01-20 11:33 UTC, kalpana19sharma commented on file_manage.rb
> +else
Use 2 space indentation and fix this in other files as well.

2022-01-20 11:33 UTC, kalpana19sharma commented on file_manage.rb
> +puts "Hello #{a}"
Add a new line at the end of the file. And handle this in all files.

2022-01-20 11:33 UTC, kalpana19sharma commented on join_array.rb
> +puts c * " "
Use proper spaces

2022-01-20 11:59 UTC, Shubham-Porwall commented
@kalpana19sharma Changes is been performed.

2022-01-24 03:08 UTC, kalpana19sharma requested changes

2022-01-24 03:08 UTC, kalpana19sharma commented on join_array.rb
> +b = Array[5,6,7,8]
Use spaces after `,`

2022-01-24 03:08 UTC, kalpana19sharma commented on join_array.rb
> +b = Array[5,6,7,8]
You can eliminate `Array` class here
```suggestion
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
```

2022-01-24 03:08 UTC, kalpana19sharma commented on join_array.rb
> +b = Array[5,6,7,8]
And use proper variable names.

2022-01-24 03:08 UTC, kalpana19sharma commented on map_method.rb
> +b = a.map{|i|  xyz(i)}
1. Use proper method and variable names
2. Use proper spaces around operators

2022-01-24 03:08 UTC, kalpana19sharma commented on no_of_word.rb
> +end
1. Use 2 space indentation
2. Use proper variable names
3. Is there any in-built method in ruby to find the frequency

2022-01-24 03:08 UTC, kalpana19sharma commented on series_printing.rb
> +user.p(1,100)
Use proper spaces around operators.

2022-01-24 10:48 UTC, kalpana19sharma requested changes

2022-01-24 10:48 UTC, kalpana19sharma commented on file_manage.rb
> +afile = File.open("test.rb" , "r+")
No need to add space before `,`. Please read the guide carefully. ```Use spaces around operators, after commas, colons and semicolons, around { and before }.```

2022-01-24 10:48 UTC, kalpana19sharma commented on file_manage.rb
> +  afile.syswrite('hello GAMMASTACK')
Either use `' '` or use `" "`. Don't use both untill and unless its necessary. We generally prefer `' '`.

2022-01-24 11:17 UTC, kalpana19sharma approved these changes

2022-01-24 11:17 UTC, merged